baseURL: https://rubenramosdev.github.io/blog/
languageCode: en-us
title: À coder | Rubén Ramos
DefaultContentLanguage: es
paginate: 4
theme: PaperMod
googleAnalytics: "G-HDH45G6EG7"

params:
  env: production
  description: "Software and architecture development articles."
  keywords: [Blog, Code, Tech, .NET, Docker, Spring boot, Java, web development, development]
  author: Rubén Ramos
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false
  
  label:
    text: "À coder |"
    iconHeight: 35

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/ruben-ramos-dev/"
    - name: github
      url: "https://github.com/rubenramosDev"

  # Toc
  UseHugoToc: true
  showtoc: true
  tocopen: false

  #comments
  comments: true
  disqusShortname: "ruben-blog"

  #blog
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  disableSpecial1stPost: false

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10

    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20

    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30

    - identifier: Search
      name: Search
      url: /search/
      weight: 40
      
    - identifier: About me
      name: About me
      url: /about-me/
      weight: 50

outputs:
  home:
    - HTML
    - JSON

  assets:
    favicon: images/favicon.ico
    favicon16x16: images/favicon.ico
    favicon32x32: images/favicon.ico
    apple_touch_icon: images/favicon.ico
    safari_pinned_tab: images/favicon.ico

  label:
    text: "Home"
    icon: images/favicon-16x16.png
    iconHeight: 35